# Generated by Django 3.1.5 on 2021-02-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('EmpRoleCode', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('EmpRole', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('EmpTypeCode', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('EmpType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryType',
            fields=[
                ('SalaryCode', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('SalType', models.CharField(max_length=30)),
            ],
        ),
    ]
