# Generated by Django 3.1.5 on 2021-02-14 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeetype',
            table='employeemanagementapp_employeetype',
        ),
    ]
