# Generated by Django 3.1.5 on 2021-02-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('empId', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('dateofbirth', models.DateTimeField()),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=500)),
                ('employeetype', models.CharField(max_length=1)),
                ('salarytype', models.CharField(max_length=1)),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
            ],
        ),
    ]
