# Generated by Django 3.1.5 on 2021-02-09 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeManagementApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetails',
            old_name='address',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='dateofbirth',
            new_name='DateofBirth',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='email',
            new_name='Email',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='empId',
            new_name='EmpId',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='employeetype',
            new_name='EmployeeRole',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='salarytype',
            new_name='EmployeeType',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='enddate',
            new_name='EndDate',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='first_name',
            new_name='First_Name',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='last_name',
            new_name='Last_Name',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='phone',
            new_name='Phone',
        ),
        migrations.RenameField(
            model_name='employeedetails',
            old_name='startdate',
            new_name='StartDate',
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='SalaryType',
            field=models.CharField(default=0, max_length=1),
            preserve_default=False,
        ),
    ]
